network:
    version: 2
    ethernets:
      eno1:
        dhcp4: false
        addresses:
          - 192.168.4.2/24
        gateway4: 192.168.4.1
        nameservers:
          addresses: [192.168.4.1]
  